name: Makefile CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install make
      run: sudo apt-get install make

    - name: Add gcc-ia16 repo
      run: sudo add-apt-repository ppa:tkchia/build-ia16

    - name: Update packages
      run: sudo apt-get update

    - name: Install gcc-ia16
      run: sudo apt-get install gcc-ia16-elf
      
    - name: Check gcc-ia16
      run: ia16-elf-gcc --version
      
    - name: Enter proper directory
      run: cd ./software/"gcc(experimental)"
      
    - name: Get contents of DIR
      run: ls

    - name: Run makefile for gcc
      run: make
